trigger:
- main

pool:
  vmImage: 'windows-latest'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: 'dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
    publishTestResults: false