trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  codecovVersion: '1.13.0'
  testProject: 'CodecovCsharpAzurePipelines.Tests'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '>=5.8'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: 'dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'
    publishTestResults: false

- script: |
    %USERPROFILE%\.nuget\packages\codecov\$(codecovVersion)\tools\codecov.exe -f "./test/$(testProject)/coverage.opencover.xml" -t $(CODECOV_TOKEN)
